# Generated by Django 3.2.9 on 2021-11-25 19:03

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.PositiveIntegerField(unique=True, verbose_name='Внешний ID покупателя')),
                ('tg_username', models.CharField(blank=True, default='', max_length=256, verbose_name='Имя покупателя в телеграм')),
                ('first_name', models.CharField(max_length=50, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('midle_name', models.CharField(max_length=50, verbose_name='Отчество')),
                ('passport_series', models.PositiveIntegerField(verbose_name='Серия паспорта')),
                ('passport_number', models.PositiveIntegerField(verbose_name='Номер паспорта')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Номер телефона')),
                ('GDPR_status', models.BooleanField(default=False, null=True, verbose_name='Согласие?')),
            ],
            options={
                'verbose_name': 'Покупатель',
                'verbose_name_plural': 'Покупатели',
            },
        ),
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Короткое название')),
                ('city', models.CharField(max_length=50, verbose_name='Город')),
                ('address', models.CharField(max_length=256, verbose_name='Адрес')),
                ('space', models.PositiveIntegerField(verbose_name='Складская площадь')),
                ('occupied_space', models.PositiveIntegerField(null=True, verbose_name='Занято м2')),
            ],
            options={
                'verbose_name': 'Склад',
                'verbose_name_plural': 'Склады',
            },
        ),
        migrations.CreateModel(
            name='Storage_item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Складская единица')),
                ('price_week', models.IntegerField(verbose_name='Цена мес.')),
                ('occupied_space', models.PositiveIntegerField(verbose_name='Занимает м2')),
                ('amount', models.PositiveIntegerField(verbose_name='Колличество')),
            ],
            options={
                'verbose_name': 'Складская единица',
                'verbose_name_plural': 'Складские единицы',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.PositiveIntegerField(null=True, unique=True, verbose_name='Номер заказа')),
                ('space_ordered', models.PositiveIntegerField(verbose_name='Арендованно м2')),
                ('price', models.PositiveIntegerField(verbose_name='Цена заказа')),
                ('start_at', models.DateTimeField(verbose_name='Начало аренды')),
                ('finished_at', models.DateTimeField(verbose_name='Конец аренды')),
                ('qr_code', models.ImageField(upload_to='', verbose_name='QR код')),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tg_bot.customer', verbose_name='Клиент')),
                ('storage', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tg_bot.storage', verbose_name='Склад')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
    ]
